language: python
sudo: false
python:
 - "3.4"
env:
  global:
   - DRF="djangorestframework==3.3.2"
   - DJANGO="django==1.9.3"
  matrix:
   - LINT=
   - LINT=1
install:
 - pip install $DJANGO
 - pip install $DRF
 - pip install flake8
script:
 - ./runtests.sh
